--- DIVISION
INSERT INTO division VALUES (1);
INSERT INTO division VALUES (2);
INSERT INTO division VALUES (3);

--- COUNTRY
INSERT INTO country(name) VALUES('D');
INSERT INTO country(name) VALUES('BRA');
INSERT INTO country(name) VALUES('A');
INSERT INTO country(name) VALUES('B');
INSERT INTO country(name) VALUES('NL');
INSERT INTO country(name) VALUES('F');
INSERT INTO country(name) VALUES('E');
INSERT INTO country(name) VALUES('CH');
INSERT INTO country(name) VALUES('DEN');
INSERT INTO country(name) VALUES('TUR/D');
INSERT INTO country(name) VALUES('CRO');
INSERT INTO country(name) VALUES('PER');
INSERT INTO country(name) VALUES('AUS');
INSERT INTO country(name) VALUES('GR');
INSERT INTO country(name) VALUES('PL');
INSERT INTO country(name) VALUES('SER/USA');
INSERT INTO country(name) VALUES('TUR');
INSERT INTO country(name) VALUES('ARM');
INSERT INTO country(name) VALUES('SER');
INSERT INTO country(name) VALUES('GAB');
INSERT INTO country(name) VALUES('CMR/D');
INSERT INTO country(name) VALUES('D/CRO');
INSERT INTO country(name) VALUES('JAP');
INSERT INTO country(name) VALUES('GHA/D');
INSERT INTO country(name) VALUES('D/USA');
INSERT INTO country(name) VALUES('GHA');
INSERT INTO country(name) VALUES('D/F');
INSERT INTO country(name) VALUES('HUN');
INSERT INTO country(name) VALUES('NGA');
INSERT INTO country(name) VALUES('FIN');
INSERT INTO country(name) VALUES('USA');
INSERT INTO country(name) VALUES('BOS');
INSERT INTO country(name) VALUES('I');
INSERT INTO country(name) VALUES('MEX');
INSERT INTO country(name) VALUES('D/E');
INSERT INTO country(name) VALUES('KOL');
INSERT INTO country(name) VALUES('FIN/D');
INSERT INTO country(name) VALUES('KOR');
INSERT INTO country(name) VALUES('CH/E');
INSERT INTO country(name) VALUES('I/D');
INSERT INTO country(name) VALUES('CZE');
INSERT INTO country(name) VALUES('POR');
INSERT INTO country(name) VALUES('SWE');
INSERT INTO country(name) VALUES('VEN');
INSERT INTO country(name) VALUES('NOR');
INSERT INTO country(name) VALUES('MKD');
INSERT INTO country(name) VALUES('COS');
INSERT INTO country(name) VALUES('BUL');
INSERT INTO country(name) VALUES('MAR/D');
INSERT INTO country(name) VALUES('EST');
INSERT INTO country(name) VALUES('CAN');
INSERT INTO country(name) VALUES('ARG');
INSERT INTO country(name) VALUES('PL/D');
INSERT INTO country(name) VALUES('USA/GHA');
INSERT INTO country(name) VALUES('TUN');
INSERT INTO country(name) VALUES('D/I');
INSERT INTO country(name) VALUES('D/TUR');
INSERT INTO country(name) VALUES('SVK');
INSERT INTO country(name) VALUES('GEO');
INSERT INTO country(name) VALUES('ALB');
INSERT INTO country(name) VALUES('ISR');
INSERT INTO country(name) VALUES('F/SEN');
INSERT INTO country(name) VALUES('SEN');
INSERT INTO country(name) VALUES('CIV');
INSERT INTO country(name) VALUES('LAT');
INSERT INTO country(name) VALUES('CGO');
INSERT INTO country(name) VALUES('D/COD');
INSERT INTO country(name) VALUES('PL/F');
INSERT INTO country(name) VALUES('SER/D');
INSERT INTO country(name) VALUES('D/PL');
INSERT INTO country(name) VALUES('MLI/F');
INSERT INTO country(name) VALUES('A/D');
INSERT INTO country(name) VALUES('GUI/F');
INSERT INTO country(name) VALUES('ROM');
INSERT INTO country(name) VALUES('ECU');
INSERT INTO country(name) VALUES('NZL');
INSERT INTO country(name) VALUES('D/BRA');
INSERT INTO country(name) VALUES('ENG');
INSERT INTO country(name) VALUES('D/CHN');
INSERT INTO country(name) VALUES('CMR');
INSERT INTO country(name) VALUES('COD');
INSERT INTO country(name) VALUES('D/SLO');
INSERT INTO country(name) VALUES('SLO');
INSERT INTO country(name) VALUES('MAR');
INSERT INTO country(name) VALUES('LIT/D');
INSERT INTO country(name) VALUES('MON');
INSERT INTO country(name) VALUES('SEN/D');
INSERT INTO country(name) VALUES('D/ALB');
INSERT INTO country(name) VALUES('ALG');
INSERT INTO country(name) VALUES('D/MAR');
INSERT INTO country(name) VALUES('USA/D');
INSERT INTO country(name) VALUES('PHI/DEN');
INSERT INTO country(name) VALUES('KAZ/D');
INSERT INTO country(name) VALUES('BFA');
INSERT INTO country(name) VALUES('');
INSERT INTO country(name) VALUES('RUS');
INSERT INTO country(name) VALUES('BRA/D');
INSERT INTO country(name) VALUES('MLI');
INSERT INTO country(name) VALUES('EGY');
INSERT INTO country(name) VALUES('LIT');
INSERT INTO country(name) VALUES('I/CMR');
INSERT INTO country(name) VALUES('ISL');
INSERT INTO country(name) VALUES('TGA/D');
INSERT INTO country(name) VALUES('BEN');
INSERT INTO country(name) VALUES('GUI');
INSERT INTO country(name) VALUES('F/ALG');
INSERT INTO country(name) VALUES('ANG');
INSERT INTO country(name) VALUES('GAM');
INSERT INTO country(name) VALUES('CAN/GHA');
INSERT INTO country(name) VALUES('F/POR');
INSERT INTO country(name) VALUES('BOS/D');
INSERT INTO country(name) VALUES('UKR');
INSERT INTO country(name) VALUES('NAM/D');
INSERT INTO country(name) VALUES('PL/USA');
INSERT INTO country(name) VALUES('AFG');

--- TEAM
INSERT INTO team VALUES(1,'FC Bayern Muenchen',1);
INSERT INTO team VALUES(2,'Borussia Dortmund',1);
INSERT INTO team VALUES(3,'Bayer Leverkusen',1);
INSERT INTO team VALUES(4,'FC Schalke 04',1);
INSERT INTO team VALUES(5,'VfL Wolfsburg',1);
INSERT INTO team VALUES(6,'1. FSV Mainz 05',1);
INSERT INTO team VALUES(7,'Borussia Moenchengladbach',1);
INSERT INTO team VALUES(8,'Hertha BSC',1);
INSERT INTO team VALUES(9,'FC Augsburg',1);
INSERT INTO team VALUES(10,'1899 Hoffenheim',1);
INSERT INTO team VALUES(11,'Hannover 96',1);
INSERT INTO team VALUES(12,'Eintracht Frankfurt',1);
INSERT INTO team VALUES(13,'SV Werder Bremen',1);
INSERT INTO team VALUES(14,'1. FC Nuernberg',1);
INSERT INTO team VALUES(15,'VfB Stuttgart',1);
INSERT INTO team VALUES(16,'Hamburger SV',1);
INSERT INTO team VALUES(17,'SC Freiburg',1);
INSERT INTO team VALUES(18,'Eintracht Braunschweig',1);
INSERT INTO team VALUES(19,'1. FC Koeln',2);
INSERT INTO team VALUES(20,'SpVgg Greuther Fuerth',2);
INSERT INTO team VALUES(21,'SC Paderborn 07',2);
INSERT INTO team VALUES(22,'Karlsruher SC',2);
INSERT INTO team VALUES(23,'1. FC Union Berlin',2);
INSERT INTO team VALUES(24,'FC St. Pauli',2);
INSERT INTO team VALUES(25,'1. FC Kaiserslautern',2);
INSERT INTO team VALUES(26,'VfR Aalen',2);
INSERT INTO team VALUES(27,'SV 1916 Sandhausen',2);
INSERT INTO team VALUES(28,'TSV 1860 Muenchen',2);
INSERT INTO team VALUES(29,'Fortuna Duesseldorf',2);
INSERT INTO team VALUES(30,'FC Ingolstadt 04',2);
INSERT INTO team VALUES(31,'FC Erzgebirge Aue',2);
INSERT INTO team VALUES(32,'FSV Frankfurt',2);
INSERT INTO team VALUES(33,'VfL Bochum',2);
INSERT INTO team VALUES(34,'Dynamo Dresden',2);
INSERT INTO team VALUES(35,'Arminia Bielefeld',2);
INSERT INTO team VALUES(36,'FC Energie Cottbus',2);
INSERT INTO team VALUES(37,'1. FC Heidenheim 1846',3);
INSERT INTO team VALUES(38,'RB Leipzig',3);
INSERT INTO team VALUES(39,'SV Darmstadt 98',3);
INSERT INTO team VALUES(40,'VfL Osnabrueck',3);
INSERT INTO team VALUES(41,'Hansa Rostock',3);
INSERT INTO team VALUES(42,'SV Wehen Wiesbaden',3);
INSERT INTO team VALUES(43,'Stuttgarter Kickers',3);
INSERT INTO team VALUES(44,'MSV Duisburg',3);
INSERT INTO team VALUES(45,'Hallescher FC',3);
INSERT INTO team VALUES(46,'Rot-Weiss Erfurt',3);
INSERT INTO team VALUES(47,'Jahn Regensburg',3);
INSERT INTO team VALUES(48,'VfB Stuttgart II',3);
INSERT INTO team VALUES(49,'Borussia Dortmund II',3);
INSERT INTO team VALUES(50,'Preussen Muenster',3);
INSERT INTO team VALUES(51,'SpVgg Unterhaching',3);
INSERT INTO team VALUES(52,'SV Elversberg',3);
INSERT INTO team VALUES(53,'Chemnitzer FC',3);
INSERT INTO team VALUES(54,'Holstein Kiel',3);
INSERT INTO team VALUES(55,'1. FC Saarbruecken',3);
INSERT INTO team VALUES(56,'Wacker Burghausen',3);